services:
  api:
    build: .
    image: medagent:latest
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./:/app
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://127.0.0.1:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s


